sonar.projectKey=Med-Aziz-Daira_devops-mini-projet
sonar.organization=med-aziz-daira
sonar.projectName=devops-mini-projet
sonar.sources=backend/src
sonar.tests=backend/tests
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/coverage/**